/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import conexao.ProdutosDAO;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import negocio.Produto;

/**
 *
 * @author felip
 */
public class Tela_excluir extends javax.swing.JFrame {

    int rgbcolor_green = Color.HSBtoRGB(0.38f, 0.93f, 0.73f);
    int rgbcolor_red = Color.HSBtoRGB(1.0f, 0.89f, 0.77f);

    Color coloruse_green = new Color(rgbcolor_green);
    Color coloruse_red = new Color(rgbcolor_red);

    /**
     * Creates new form Tela_excluir
     */
    public Tela_excluir() throws SQLException {
        initComponents();
        setIcon();
        DefaultTableModel table = (DefaultTableModel) jTProdutos.getModel();
        jTProdutos.setRowSorter(new TableRowSorter(table));

        readJTable();
    }

    public void readJTable() throws SQLException {
        ProdutosDAO carro = new ProdutosDAO();

        DefaultTableModel table = (DefaultTableModel) jTProdutos.getModel();

        List<Produto> listaDeCarros;
        listaDeCarros = new ArrayList<>();

        listaDeCarros = carro.obterListaDeCarros();

        for (Produto carroLocal : listaDeCarros) { // Iterator: Para cada carro na lista de carros...

            table.addRow(new Object[]{
                carroLocal.getIdProdutos(),
                carroLocal.getProduto(),});

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_excluir = new javax.swing.JTextField();
        bt_excluir_id = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_excluir_nome = new javax.swing.JButton();
        produto_excluir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        id_stt = new javax.swing.JLabel();
        prod_stt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir Produtos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_excluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(id_excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 59, 153, -1));

        bt_excluir_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_excluir_id.setText("Excluir pelo ID");
        bt_excluir_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_idActionPerformed(evt);
            }
        });
        getContentPane().add(bt_excluir_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, 153, -1));

        jPanel1.setBackground(new java.awt.Color(18, 64, 121));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digite o ID ");

        bt_excluir_nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_excluir_nome.setText("Excluir pelo Nome");
        bt_excluir_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir_nomeActionPerformed(evt);
            }
        });

        produto_excluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Digite o nome do Produto");

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTProdutos);
        if (jTProdutos.getColumnModel().getColumnCount() > 0) {
            jTProdutos.getColumnModel().getColumn(0).setResizable(false);
            jTProdutos.getColumnModel().getColumn(1).setResizable(false);
        }

        id_stt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id_stt.setForeground(new java.awt.Color(255, 255, 255));

        prod_stt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        prod_stt.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(id_stt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produto_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(bt_excluir_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prod_stt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(produto_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_excluir_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id_stt, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(prod_stt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 1, 480, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_excluir_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_idActionPerformed

        Produto carro = new Produto();
        ProdutosDAO car = new ProdutosDAO();

        List<Produto> listaDeCarros;
        listaDeCarros = new ArrayList<>();

        try {
            listaDeCarros = car.obterListaDeCarros();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_atualizar.class.getName()).log(Level.SEVERE, null, ex);
        }

        int id, id_atual, ok = 0;

        String status_excluir = "Excluido com sucesso!";

        try {
            id = Integer.parseInt(id_excluir.getText());

            for (Produto carroLocal : listaDeCarros) { // Iterator: Para cada carro na lista de carros...
                id_atual = carroLocal.getIdProdutos();

                if (id_atual == id) {
                    ok = 1;
                }
            }

            if (ok == 0) {
                id_stt.setText("ID Não Encontrado");

            } else if (ok == 1) {
                car.deletarPorId(id);

                Return_excluir st = new Return_excluir(status_excluir);

                Tela_excluir.this.dispose();

                st.setVisible(true);
            }

        } catch (Exception e) {
            id_stt.setText("Informe um Número");
            id_excluir.setBackground(coloruse_red);
        }


    }//GEN-LAST:event_bt_excluir_idActionPerformed

    private void bt_excluir_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir_nomeActionPerformed
        Produto carro = new Produto();
        ProdutosDAO car = new ProdutosDAO();

        List<Produto> listaDeCarros;
        listaDeCarros = new ArrayList<>();

        try {
            listaDeCarros = car.obterListaDeCarros();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_atualizar.class.getName()).log(Level.SEVERE, null, ex);
        }

        String produto, prod_atual = "";
        String status_excluir = "Excluido com sucesso!";
        int ok = 0;

        try {
            produto = produto_excluir.getText();

            if (produto_excluir.getText().trim().isEmpty()) {
                prod_stt.setText("Informe o nome do produto");
                produto_excluir.setBackground(coloruse_red);

            } else {

                for (Produto carroLocal : listaDeCarros) { // Iterator: Para cada carro na lista de carros...
                    prod_atual = carroLocal.getProduto();

                    if (prod_atual.equals(produto)) {
                        ok = 1;

                        car.deletarPorProduto(produto);

                        Return_excluir st = new Return_excluir(status_excluir);

                        Tela_excluir.this.dispose();

                        st.setVisible(true);

                    }

                }

                if (ok == 0) {
                    prod_stt.setText("Produto Não Existe");
                    produto_excluir.setBackground(coloruse_red);
                }

            }

        } catch (Exception e) {

        }


    }//GEN-LAST:event_bt_excluir_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Tela_excluir().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Tela_excluir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_excluir_id;
    private javax.swing.JButton bt_excluir_nome;
    private javax.swing.JTextField id_excluir;
    private javax.swing.JLabel id_stt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JLabel prod_stt;
    private javax.swing.JTextField produto_excluir;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
