/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import telas.Return_inserir;
import conexao.ProdutosDAO;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import negocio.Produto;

/**
 *
 * @author felipe.psantos44
 */
public class Tela_inserir extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela_inserir() {
        initComponents();
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prod_tela = new javax.swing.JTextField();
        valor_tela = new javax.swing.JTextField();
        custo_tela = new javax.swing.JTextField();
        est_tela = new javax.swing.JTextField();
        vm_tela = new javax.swing.JTextField();
        inserindo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setBackground(new java.awt.Color(255, 204, 102));
        setForeground(new java.awt.Color(255, 204, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prod_tela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(prod_tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 35, 200, 30));

        valor_tela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(valor_tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 30));

        custo_tela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(custo_tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 165, 200, 30));

        est_tela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(est_tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 200, 30));

        vm_tela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(vm_tela, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 200, 30));

        inserindo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inserindo.setBorderPainted(false);
        inserindo.setContentAreaFilled(false);
        inserindo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inserindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserindoActionPerformed(evt);
            }
        });
        getContentPane().add(inserindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 240, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Tela Inserir.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inserindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserindoActionPerformed
        // TODO add your handling code here:
         Produto carro = new Produto();
         
         String status_inserir = "Produto Cadastrado!";
         
         String produto = "";
         int vendamedia = 0;
         int estoque = 0;
         double custo = 0;
         double valor = 0;
         double lucro = 0;
         int mes = 0;
         
         int campos_ok = 0;
          
         int rgbcolor_green = Color.HSBtoRGB(0.38f,0.93f,0.73f);  
         int rgbcolor_red = Color.HSBtoRGB(1.0f,0.89f,0.77f); 
         
         Color coloruse_green = new Color(rgbcolor_green);
         Color coloruse_red = new Color(rgbcolor_red);
       
         try{
             
             produto = prod_tela.getText();
         
             if(prod_tela.getText().trim().isEmpty()){
                prod_tela.setBackground(coloruse_red);
               
                
             } else {
                 prod_tela.setBackground(coloruse_green);
                 campos_ok += 1;
             }

            try { 
                valor = Double.parseDouble(valor_tela.getText());
                valor_tela.setBackground(coloruse_green);
                campos_ok += 1;

               } catch (Exception e) {
                 valor_tela.setBackground(coloruse_red);

               }
            
            try { 
                 custo = Double.parseDouble(custo_tela.getText());
                 custo_tela.setBackground(coloruse_green);
                 campos_ok += 1;

               } catch (Exception e) {
                 custo_tela.setBackground(coloruse_red);

               }

            try { 
                 vendamedia = Integer.parseInt(vm_tela.getText());
                 vm_tela.setBackground(coloruse_green);
                 campos_ok += 1;

               } catch (Exception e) {
                 vm_tela.setBackground(coloruse_red);

               }

            try { 
                 estoque = Integer.parseInt(est_tela.getText());
                 est_tela.setBackground(coloruse_green);
                 campos_ok += 1;

               } catch (Exception e) {
                 est_tela.setBackground(coloruse_red);

               }
            
            System.out.println("Campos ok = " + campos_ok);

  
            lucro = valor - custo;

            mes = estoque / vendamedia;

            if (campos_ok == 5) {

                 carro.setProduto(produto);
                 carro.setValor(valor);
                 carro.setCusto(custo);
                 carro.setLucro(lucro);
                 carro.setVendamedia(vendamedia);
                 carro.setEstoque(estoque);

                 ProdutosDAO cD = new ProdutosDAO();
                 cD.insereCarro(carro, mes, produto);
                 cD.update_data_inserir(produto, mes);

                 Return_inserir st = new Return_inserir(status_inserir);

                 Tela_inserir.this.dispose();

                 st.setVisible(true);
            }

               
            
         } catch (Exception e) {
             status_inserir = "ERRO AO INSERIR";
             
         }
        
            
            
            
            
    }//GEN-LAST:event_inserindoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_inserir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_inserir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custo_tela;
    private javax.swing.JTextField est_tela;
    public javax.swing.JButton inserindo;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField prod_tela;
    private javax.swing.JTextField valor_tela;
    private javax.swing.JTextField vm_tela;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
